### ISSUE TITLE
Feature 1: User can search for breweries

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for breweries based off a city.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able type into the search bar to search for breweries that match the search word.

 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-01 at 4 33 12 PM](https://user-images.githubusercontent.com/96788421/156272109-f9a81d1a-b72d-49cc-8642-896e7345cf5e.png)
![Screen Shot 2022-03-01 at 4 32 54 PM](https://user-images.githubusercontent.com/96788421/156272111-296f4264-541d-48a5-9d1b-0c17833133eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add the necessary HTML elements and content to fit the wire frame
- [x] Add a div for the data-view
- [x] Make the input required
- [x] Add the necessary CSS to fit the styling of the wireframes
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Set up a data model
- [x] Add a query selector and event listener for the input
- [x] Concatenate the search with the GET request
- [x] Verify the search is bring up the target result
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
