### ISSUE TITLE
Feature 2: User can view their search

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the results of their search

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will search for breweries in the search bar input and will be able to see the results. Pressing on the Icon will take them back to the home page.

 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-03 at 3 55 39 PM](https://user-images.githubusercontent.com/96788421/156673091-60963c68-454a-4e86-822e-01cf37d57ff0.png)
![Screen Shot 2022-03-03 at 3 55 06 PM](https://user-images.githubusercontent.com/96788421/156673095-869e3197-0f9b-4061-82aa-f899eae1fe40.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a new data-view results DIV
- [x] Add an empty unordered list to the new DIV
- [x] Add ‘dummy’ HTML and CSS  to the unordered list
- [x] Check that the results list looks good on both mobile and desktop screens.
- [x] Create a function to render a DOM tree based off the dummy results
- [x] Loop through the search results list to to create the actual DOM tree on the page
- [x] Remove the dummy HTML elements
- [x] Ensure that the search renders the DOM tree
- [x] Ensure that the header returns the user to the search page. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
