### ISSUE TITLE
Feature 3: User can view more info of the brewery

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the icon to see additional information of the search

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the 3 dot icon to see more information for the search. The user will then be able to contract the view and see less information by clicking on the up caret

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-03-04 at 11 45 46 AM](https://user-images.githubusercontent.com/96788421/156831881-ad8c4324-ed34-40da-8633-c014dd66cd60.png)
![Screen Shot 2022-03-04 at 11 49 37 AM](https://user-images.githubusercontent.com/96788421/156831883-0d2be30e-f0da-4a7d-9de8-f2f9c163342c.png)
![Screen Shot 2022-03-04 at 11 49 45 AM](https://user-images.githubusercontent.com/96788421/156831886-b413b947-1203-4328-85ad-2190ad6efcbe.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add the 3 dot icon onto the page when the results are rendered
- [x] add an event listener and function to the icon
- [x] retrieve the additional info from the API
- [x] render the additional info of the specific result for the user to view it
- [x] add the up caret icon when the user view is expanded
- [x] add an event listener and function to the new icon 
- [x] have the user be able to contract the view and get rid of the additional info on the new icon
- [x] test functionality and look for bugs
- [x] ensure that pressing the new icons does not alter any previous functionality
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
