### ISSUE TITLE
Feature 4: User can bookmark a search result

### ISSUE THREAD

**Issue by Yi-Jacob** [Yi-Jacob/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can bookmark a search that they are interested in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click the PLUS icon to save the specific brewery to local storage.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-01 at 4 47 13 PM](https://user-images.githubusercontent.com/96788421/156273380-16f38a47-8517-4359-99ed-6a8c5c189685.png)
![Screen Shot 2022-03-01 at 4 47 30 PM](https://user-images.githubusercontent.com/96788421/156273384-28baf5c4-e379-4211-8b65-eacf8766a4ac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add the necessary HTML and CSS for the bookmark icon
- [ ] ensure that the icon looks good for both mobile and desktop
- [ ] have the + button on each of the results
- [ ] make the + button turn into a - button when the user clicks it
- [ ] ensure the data model can fit the necessary informations
- [ ] add an entry ID to each result
- [ ] add an event listener to the icon
- [ ] ensure that the specific result is saved in local storage
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
